apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://vmauth:8427/

  - name: VictoriaMetrics
    type: victoriametrics-metrics-datasource
    access: proxy
    url: http://vmauth:8427/
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.24.0
