services:
  user_service:
    platform: linux/amd64
    image: ${USER_SERVICE_IMAGE}
    container_name: user_service
    restart: unless-stopped
    environment:
      - ENV=production
    command: "/user_service"
