services:
  gateway:
    container_name: gateway
    build:
      context: ../nginx
    image: gateway:0.0.1
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "81:80"
    depends_on:
      - auth_service
      - user_service
      - file_service
