services:
  grafana:
    container_name: grafana
    build:
      context: ../grafana
      dockerfile: Dockerfile
    image: grafana-monitoring:v0.0.1
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost/grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      prometheus:
        condition: service_healthy

volumes:
  grafana-data: