services:
  auth_service:
    platform: linux/amd64
    image: ${AUTH_SERVICE_IMAGE}
    container_name: auth_service
    restart: unless-stopped
    depends_on:
      - file_service
      - user_service
      - notification_service
    environment:
      - ENV=production
    command: "/auth_service"
