services:
  auth_service:
    platform: linux/amd64
    image: ${AUTH_SERVICE_IMAGE}
    container_name: auth_service
    restart: unless-stopped
    depends_on:
      - file_service
      - user_service
      - notification_service
    environment:
      - ENV=production
    command: "/auth_service"
  
  auth_service-healthcheck:
    image: curlimages/curl:latest
    entrypoint: >
      /bin/sh -c "until curl -sf http://auth_service/healthy; do sleep 2; done; sleep infinity"
    depends_on:
      auth_service:
        condition: service_started