services:
  redis:
    image: redis:7.2
    container_name: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]

volumes:
  redis-data:
