services:
  gateway:
    container_name: gateway
    build:
      context: ../nginx
    image: app-gateway:v0.0.1
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "81:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx_status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      auth_service:
        condition: service_started
      user_service:
        condition: service_started
      file_service:
        condition: service_started
      notification_service:
        condition: service_started
    
