services:
  user_db:
    build:
      context: ../db
      dockerfile: Dockerfile
    image: postgres_with_init:v0.0.1
    container_name: user_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - user_db_data:/var/lib/postgresql/data

  auth_db:
    build:
      context: ../db
      dockerfile: Dockerfile
    image: postgres_with_init:v0.0.1
    container_name: auth_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
  user_db_data:
