services:
  file_service:
    platform: linux/amd64
    image: file_service:${FILE_SERVICE_VERSION}
    container_name: file_service
    restart: unless-stopped
    environment:
      - ENV=production
    command: "/file_service"
