services:
  notification_service:
    platform: linux/amd64
    image: ${NOTIFICATION_SERVICE_IMAGE}
    container_name: notification_service
    restart: unless-stopped
    environment:
      - ENV=production
    command: "/notification_service"