services:
  file_service:
    platform: linux/amd64
    image: ${FILE_SERVICE_IMAGE}
    container_name: file_service
    restart: unless-stopped
    environment:
      - ENV=production
    command: "/file_service"
