services:
  prometheus:
    build:
      context: ../prometheus
    container_name: prometheus
    image: prometheus-monitoring:v0.0.1
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - prometheus-data:/prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  prometheus-data: