services:
  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z-cpuv1
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: ${MINIO_PROMETHEUS_AUTH_TYPE}
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data  --address ":80" --console-address ":9001"

volumes:
  minio-data:
