services:
  user_service:
    platform: linux/amd64
    image: user_service:${USER_SERVICE_VERSION}
    container_name: user_service
    restart: unless-stopped
    environment:
      - ENV=production
    command: "/user_service"
